#!/bin/bash

set -e

DBPATH=/scratch/postgres

if [ -d "$DBPATH" ]
then
    /etc/init.d/postgresql stop
fi

rm -rf $DBPATH
mkdir -p $DBPATH

/usr/lib/postgresql/15/bin/pg_ctl init -D /scratch/postgres
cp /etc/postgresql/15/main/pg_hba.conf /scratch/postgres/pg_hba.conf
/etc/init.d/postgresql start

createdb buildbot
psql -c 'create database bbtest WITH ENCODING UTF8 TEMPLATE template0 ;'
psql -c 'create database bbtest0 WITH ENCODING UTF8 TEMPLATE template0 ;'
psql -c 'create database bbtest1 WITH ENCODING UTF8 TEMPLATE template0 ;'
psql -c 'create database bbtest2 WITH ENCODING UTF8 TEMPLATE template0 ;'
psql -c 'create database bbtest3 WITH ENCODING UTF8 TEMPLATE template0 ;'
psql -c 'create database bbtest4 WITH ENCODING UTF8 TEMPLATE template0 ;'
psql -c 'create database bbtest5 WITH ENCODING UTF8 TEMPLATE template0 ;'
psql -c 'create database bbtest6 WITH ENCODING UTF8 TEMPLATE template0 ;'
psql -c 'create database bbtest7 WITH ENCODING UTF8 TEMPLATE template0 ;'
