#!/bin/bash

set -e

DBPATH=/scratch/mysql

if [ -d "$DBPATH" ]
then
    /etc/init.d/mariadb stop
fi

rm -rf $DBPATH
mkdir -p $DBPATH
mysql_install_db --auth-root-authentication-method=normal
/etc/init.d/mariadb start --skip-grant-tables

mysql -e 'create database bbtest;'
mysql -e 'create database bbtest0;'
mysql -e 'create database bbtest1;'
mysql -e 'create database bbtest2;'
mysql -e 'create database bbtest3;'
mysql -e 'create database bbtest4;'
mysql -e 'create database bbtest5;'
mysql -e 'create database bbtest6;'
mysql -e 'create database bbtest7;'
